project_id = "badbbhaujbavqxiwvyzu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[fetch-company-logo.functions]]
verify_jwt = true